# Generated by Django 5.2.6 on 2025-10-06 14:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('nida_number', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('car_name', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('car_type', models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Pickup', 'Pickup'), ('Van', 'Van'), ('Coupe', 'Coupe')], max_length=10)),
                ('number_of_seats', models.IntegerField(choices=[(2, '2 seats'), (3, '3 seats'), (4, '4 seats'), (5, '5 seats'), (6, '6 seats'), (7, '7 seats')], validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(7)])),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='drivers/photos/')),
                ('id_photo', models.ImageField(blank=True, null=True, upload_to='drivers/ids/')),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to='drivers/cars/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_driver',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
