# Generated by Django 5.2.6 on 2025-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('start_address', models.CharField(blank=True, max_length=255)),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('end_address', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.FloatField()),
                ('duration_min', models.FloatField()),
                ('geometry', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
