# Generated by Django 5.2.6 on 2025-10-06 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.driver'),
        ),
    ]
