# Generated by Django 5.2.6 on 2025-10-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0003_alter_otpverification_uuid_alter_user_uuid_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'otp_type', 'is_verified'], name='otp_user_type_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['recipient', 'otp_type'], name='otp_recipient_type_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'is_verified', '-created_at'], name='otp_user_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['expires_at'], name='otp_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='user_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['uuid'], name='user_uuid_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'email'], name='user_active_email_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'phone_number'], name='user_active_phone_idx'),
        ),
    ]
